---

- hosts: all
  vars:
    sysctl_config:
      net.ipv4.ip_forward: 1
      # net.bridge.bridge-nf-call-iptables: 1
      # net.bridge.bridge-nf-call-ip6tables: 1
  tasks:

    - name: Install apt packages
      become: true
      ansible.builtin.apt:
        update_cache: yes
        pkg:
          - linux-image-generic
          - linux-headers-5.4.0-162-generic
          - gcc 
          - g++ 
          - cmake 
          - autoconf 
          - libtool 
          - pkg-config 
          - libmnl-dev 
          - libyaml-dev
          - qemu-guest-agent
    - name: Install microk8s 1.26
      become: true
      community.general.snap:
        name:
          - microk8s
        classic: true
        channel: 1.26
    - name: Enable microk8s addons
      become: true
      ansible.builtin.command:
        cmd: "microk8s.enable {{ item }} "
      loop:
        - storage
        - community
        - dns
        - multus
        - ingress
    - name: Run sysctl --system
      become: true
      ansible.builtin.command:
        cmd: "sysctl --system"
    - name: Change various sysctl-settings
      become: true
      ansible.builtin.sysctl:
        name: '{{ item.key }}'
        value: '{{ item.value }}'
        sysctl_set: yes
        state: present
        reload: yes
      with_dict: '{{ sysctl_config }}'
    - name: Clone gpt5g
      ansible.builtin.git:
        repo: https://github.com/free5gc/gtp5g.git
        dest: /home/packer/gtp5g
    - name: Run make clean && make
      ansible.builtin.shell: make clean && make
      args:
        chdir: /home/packer/gtp5g
    - name: Run 'install' target as root
      become: true
      community.general.make:
        chdir: "/home/packer/gtp5g"
        target: install
    - name: Enable GRUB default
      become: true
      ansible.builtin.lineinfile:
        path: /etc/default/grub
        line: "GRUB_DEFAULT='Advanced options for Ubuntu>Ubuntu, with Linux 5.4.0-162-generic'"
        state: present
   #   notify: update-grub
    - name: Insert ipv4 fowarding in cni configuration
      become: true
      ansible.builtin.replace:
        path: /var/snap/microk8s/current/args/cni-network/cni.yaml
        regexp: "(?m){{after}}"
        replace: "{{settings}}"
      vars:
        after: |-
          "plugins": \[
                  {
        settings: |-
          "plugins": [
                  {
                    "container_settings": { "allow_ip_forwarding": true },
    - name: Enable GRUB default
      become: true
      ansible.builtin.lineinfile:
        path: /var/snap/microk8s/current/args/kubelet
        line: "--allowed-unsafe-sysctls 'net.ipv4.ip_forward'"
        state: present
    - name: Apply cni configuration
      become: true
      ansible.builtin.command:
        cmd: "microk8s.kubectl apply -f /var/snap/microk8s/current/args/cni-network/cni.yaml"
